name: Build and Publish Extension

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build extension
        run: npm run build

      - name: Update manifest version
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        run: |
          VERSION=$(echo ${{ github.ref }} | sed 's/^refs\/tags\///')
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" manifest.json
          git add manifest.json
          git commit -m "Bump version to $VERSION"

      - name: Create release
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG=$(echo ${{ github.ref }} | sed 's/^refs\/tags\///')
          gh release create "$RELEASE_TAG" -t "$RELEASE_TAG" -n "Release $RELEASE_TAG" -F CHANGELOG.md "dist/*.zip"
